version = 0.1
[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "delay-post-staging"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1js61lddvzyha"
s3_prefix = "delay-post-staging"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"staging\" EventBus=\"delaygram-event-bus-staging\" AuthArn=\"VhJGi8jOl\""
image_repositories = []
